# permissions for end users to edit acls.
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: clusterrole
    app.kubernetes.io/instance: acl-editor-role
    app.kubernetes.io/component: rbac
    app.kubernetes.io/created-by: lfgw-config-operator
    app.kubernetes.io/part-of: lfgw-config-operator
    app.kubernetes.io/managed-by: kustomize
  name: acl-editor-role
rules:
- apiGroups:
  - controls.lfgw.io
  resources:
  - acls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - controls.lfgw.io
  resources:
  - acls/status
  verbs:
  - get
