---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: manager-role
rules:
- apiGroups:
  - controls.lfgw.io
  resources:
  - acls
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - controls.lfgw.io
  resources:
  - acls/finalizers
  verbs:
  - update
- apiGroups:
  - controls.lfgw.io
  resources:
  - acls/status
  verbs:
  - get
  - patch
  - update
